import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`text-dark bg-white `}>
            <div className={`px-4 xl:px-[100px]`}>
               <Header />
               <div className={``}>{children}</div>
               <Footer />
            </div>
         </body>
      </html>
   );
}
